#!/bin/bash
set -e

cd "$(dirname "$0")/.."

# Bump patch version
npm version patch --no-git-tag-version

# Get new version
VERSION=$(node -p "require('./package.json').version")

# Update version.ts
echo "// Auto-generated by deploy script - do not edit manually" > src/version.ts
echo "export const VERSION = \"$VERSION\";" >> src/version.ts

echo "📦 Version bumped to $VERSION"

# Build (vite copies public/ → dist/, then generate updates public/)
npm run build

# Sync generated token pages from public/ to dist/
# (generate-token-pages.ts writes to public/, but vite already copied it)
cp -r public/token/* dist/token/ 2>/dev/null || true
cp -r public/api/* dist/api/ 2>/dev/null || true
cp public/sitemap.xml dist/sitemap.xml 2>/dev/null || true

echo "✅ Build complete - v$VERSION ($(ls dist/token/ | wc -l | tr -d ' ') token pages)"
