#!/bin/bash
set -e

cd "$(dirname "$0")/.."

# Bump patch version
npm version patch --no-git-tag-version

# Get new version
VERSION=$(node -p "require('./package.json').version")

# Update version.ts
echo "// Auto-generated by deploy script - do not edit manually" > src/version.ts
echo "export const VERSION = \"$VERSION\";" >> src/version.ts

echo "📦 Version bumped to $VERSION"

# Build
npm run build

echo "✅ Build complete - v$VERSION"
